version: '3'
services:
  web:
    build: '.'
    ports:
      - '5000:5000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=flats_db
      - POSTGRES_USER=flats_user
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data: